#!/usr/bin/env node
var web3 = require("web3")
var rpc = 'http://localhost:8545'

if(process.argv[2] === "help" || process.argv[2] === "--help" || process.argv[2] === "-h" || process.argv[2] === undefined ){
	console.log("\nThis utility returns the balance of an account, in ether")
	console.log("This requires running an ethereum node with rpc enabled at http://localhost:8545")
	console.log("\nusage: getbalance <account>\n")
	process.exit()
}

consol.log("\nBalance: " + web3.fromWei(web3.eth.getBalance(process.argv[2]),"ether") + "\n")
