#!/usr/bin/env node

if(process.argv[2] === "help" || process.argv[2] === "--help" || process.argv[2] === "-h" || process.argv[2] === undefined ){
	console.log("\nThis utility creates a new ethereum account")
	console.log("It places the private key in a file named as the account number") 
	console.log("\nusage: newaccount <facemash entropy>\n")
	process.exit()
}

var rand = require("random-seed").create()
var ethutil = require("ethereumjs-util")
var fs = require("fs")

rand.addEntropy(process.argv[2])

var rBytes = new Buffer(32)
for(var i = 0; i < 32; i++){
  rBytes[i] = rand(256)
}

addr = "0x" + ethutil.privateToAddress(rBytes).toString('hex')
priv = "0x" + rBytes.toString('hex')


fs.writeFileSync(addr,priv)

console.log("\n\naddress:\n" + addr)
console.log("\n\nprivate key:\n" + priv + "\n\n")